# ════════════════════════════════════════
# CAPÍTULO 11 — AGRADECIMIENTOS (ACTUALIZADO)
# ════════════════════════════════════════
H1('11', 'AGRADECIMIENTOS')

H2('11.1 — A los creadores de contenido que inspiraron este proyecto')
P('Este proyecto no sería posible sin la inspiración y el conocimiento compartido por creadores de contenido en el mundo de la inteligencia artificial, el desarrollo de software y el emprendimiento. En un ecosistema donde la información evoluciona tan rápidamente, contar con referencias que explican, motivan y muestran el camino es fundamental para cualquier persona que quiera adentrarse en estas tecnologías y aplicarlas profesionalmente.')
P('Quiero agradecer especialmente a cuatro personas cuyos canales y contenido han sido determinantes en mi decisión de apostar por la inteligencia artificial como herramienta profesional y de desarrollo personal. Cada uno de ellos, desde su enfoque particular, ha contribuido a mi formación y a mi motivación para emprender este camino.')

H2('11.2 — MiduDev (Miguel Ángel Durán)')
P('MiduDev es el canal de Miguel Ángel Durán, uno de los divulgadores de desarrollo web más influyentes en habla hispana. Su canal de YouTube (@midulive) cubre desde fundamentos de JavaScript y React hasta las últimas novedades en frameworks y herramientas de inteligencia artificial aplicada al desarrollo. En Instagram (@midulive) comparte contenido más visual y directo sobre consejos de programación, tecnología y productividad.')
P('Su capacidad para explicar conceptos complejos de forma clara y su honestidad al mostrar tanto los aciertos como los errores en el desarrollo han sido una fuente constante de aprendizaje. Fue a través de sus vídeos sobre inteligencia artificial aplicada al desarrollo web donde empecé a entender el verdadero potencial de herramientas como Claude, Copilot y los agentes autónomos de código. Su contenido sobre cómo integrar IA en el flujo de trabajo diario de un desarrollador fue el detonante para aplicar estas técnicas en este proyecto.')

H2('11.3 — MooreDev')
P('MooreDev es un divulgador de inteligencia artificial y tecnología en español que se ha convertido en una referencia para todos los que quieren entender cómo aplicar la IA en entornos prácticos y profesionales. Su canal de YouTube y su presencia en Instagram ofrecen análisis detallados de herramientas de IA, comparativas entre modelos, casos de uso reales en empresas y reflexiones sobre el futuro de la tecnología.')
P('Su enfoque práctico y orientado a resultados me ayudó a entender que la IA no es solo una herramienta de código, sino un habilitador transversal para cualquier proceso empresarial. Sus análisis sobre casos de uso reales de IA en empresas, desde automatización de procesos hasta análisis de datos, fueron clave para dimensionar el impacto que estas tecnologías pueden tener en el mundo laboral y para orientar mi carrera hacia la integración de IA en entornos corporativos.')

H2('11.4 — Juan Pérez Navarro')
P('Juan Pérez Navarro es un divulgador especializado en inteligencia artificial que comparte contenido tanto en YouTube como en Instagram, centrado en explicar las capacidades de la IA de forma accesible para todo tipo de públicos. Su enfoque abarca desde tutoriales prácticos sobre herramientas de IA generativa hasta análisis profundos sobre el impacto de la inteligencia artificial en el mercado laboral y la sociedad.')
P('Su visión sobre cómo la IA puede transformar procesos empresariales completos — desde la creación de herramientas internas que ahorran miles de euros a las empresas, hasta el análisis avanzado de datos y la gestión de KPIs — resonó profundamente con mi objetivo profesional. Gracias a su contenido entendí que el verdadero valor de la IA no está en generar código más rápido, sino en identificar las necesidades reales de una empresa y construir soluciones a medida que resuelvan problemas concretos, exactamente lo que este proyecto representa.')

H2('11.5 — Anas Analousi')
P('Anas Analousi es un emprendedor y creador de contenido que se ha hecho conocido por su enfoque directo y motivacional sobre el emprendimiento y la inteligencia artificial. Su canal de YouTube muestra la mentalidad de un joven emprendedor que ha conseguido construir un negocio alrededor de la IA, demostrando que la edad no es una barrera cuando se tiene la determinación y la visión adecuadas.')
P('Recuerdo verlo por primera vez y quedar impresionado al ver a un chaval joven hablando de trabajar "con la idea", sin importar los detalles técnicos, sino centrándose en ejecutar y en generar valor real. Su filosofía de "simplemente hazlo, empieza, no esperes a tenerlo todo perfecto" fue el empujón que necesitaba para lanzarme a proyectos como este, donde la ejecución y la iteración constante pesan más que la planificación excesiva. A veces, el primer paso es el más difícil, y su contenido me ayudó a darlo.')

H2('11.6 — Motivación profesional y perspectiva de futuro')
P('Más allá de los agradecimientos personales, este proyecto representa mi convicción de que la inteligencia artificial va a ser una herramienta fundamental en el entorno empresarial de los próximos años. Mi objetivo profesional es precisamente ese: cruzar la inteligencia artificial dentro de las empresas, adaptándola a sus necesidades específicas, respetando los estándares de privacidad y seguridad, y construyendo soluciones a medida que generen un retorno real.')
P('La capacidad de crear programas propios para una empresa, evitando depender de proveedores externos y sus costes recurrentes, es una de las aplicaciones más valiosas de la IA en el mundo corporativo. Desde procesos de análisis de datos y gestión de KPIs hasta la automatización de flujos de trabajo y la detección de errores, las posibilidades son prácticamente infinitas cuando se combina el conocimiento técnico con la visión de negocio.')
P('Este proyecto es el primer paso en ese camino: una demostración de que un desarrollador individual, armado con las herramientas de IA adecuadas y la motivación suficiente, puede crear soluciones profesionales que compiten con las de equipos enteros. Y ese es solo el principio. El futuro que veo es uno donde la IA no reemplaza a los profesionales, sino que los amplifica, permitiéndoles centrarse en lo que realmente importa: entender los problemas, diseñar soluciones y aportar valor real a las organizaciones.')